### ISSUE TITLE
不支持对classloader的处理

### ISSUE THREAD

**Issue by BACMiao** [guxingke/mini-jvm#38]
您好，在执行如以下包含classloader代码时，mini-jvm好像无法解析。
```
    try {
      Class cls = Class.forName("TestClass");
      cl = cls.getClassLoader();
      cl.getResource("name");
    } catch (Exception e) { 
      System.out.println(-1);
    }
```

报错如下所示：
```
Exception in thread "main" java.lang.NullPointerException
	at com.gxk.jvm.instruction.references.InvokeVirtualInst.execute(InvokeVirtualInst.java:80)
	at com.gxk.jvm.interpret.Interpreter.execute(Interpreter.java:53)
	at com.gxk.jvm.interpret.Interpreter.runMain(Interpreter.java:77)
	at com.gxk.jvm.VirtualMachine.run(VirtualMachine.java:79)
	at com.gxk.jvm.Main.main(Main.java:24)
```

**Comment by guxingke** [comment]
@BACMiao 已知问题，当前尚不支持 ClassLoader ，以及与之相关的业务。

**Comment by BACMiao** [comment]
非常感谢，请问能否提供一些解决思路和想法

**Comment by guxingke** [comment]
1. 当前实现下，所有的类都是由启动类加载器加载的，没有自定义类加载器，这是第一步要做的。
2. 配合类加载器需要实现一些 native 方法。
3. 不建议做这些

@BACMiao

**Comment by BACMiao** [comment]
> 1. 当前实现下，所有的类都是由启动类加载器加载的，没有自定义类加载器，这是第一步要做的。
> 2. 配合类加载器需要实现一些 native 方法。
> 3. 不建议做这些
> 
> @BACMiao

非常感谢
